name: py36
channels:
  - defaults
dependencies:
  - _tflow_select=2.3.0
  - absl-py=0.6.1
  - asn1crypto=0.24.0
  - astor=0.7.1
  - blas=1.0
  - boto=2.49.0
  - boto3=1.9.35
  - botocore=1.12.35
  - c-ares=1.15.0
  - ca-certificates=2018.03.07
  - certifi=2018.11.29
  - cffi=1.11.5
  - chardet=3.0.4
  - cryptography=2.4.1
  - cymem=2.0.2
  - cytoolz=0.9.0.1
  - dill=0.2.8.2
  - docutils=0.14
  - gast=0.2.0
  - gensim=3.4.0
  - grpcio=1.16.1
  - h5py=2.8.0
  - hdf5=1.10.2
  - idna=2.7
  - intel-openmp=2019.1
  - jmespath=0.9.3
  - keras=2.2.4
  - keras-applications=1.0.6
  - keras-base=2.2.4
  - keras-preprocessing=1.0.5
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libopenblas=0.3.3
  - libprotobuf=3.6.1
  - markdown=3.0.1
  - mkl=2018.0.3
  - mkl_random=1.0.1
  - msgpack-numpy=0.4.3.2
  - msgpack-python=0.5.6
  - murmurhash=1.0.1
  - ncurses=6.1
  - nltk=3.3.0
  - nomkl=3.0
  - numpy=1.15.4
  - numpy-base=1.15.4
  - openssl=1.1.1a
  - pandas=0.23.4
  - pip=18.1
  - plac=0.9.6
  - preshed=2.0.1
  - protobuf=3.6.1
  - pycparser=2.19
  - pyopenssl=18.0.0
  - pysocks=1.6.8
  - python=3.6.7
  - python-dateutil=2.7.5
  - pytz=2018.7
  - pyyaml=3.13
  - readline=7.0
  - regex=2018.11.07
  - requests=2.20.1
  - s3transfer=0.1.13
  - scikit-learn=0.20.1
  - scipy=1.1.0
  - setuptools=40.6.2
  - six=1.12.0
  - smart_open=1.7.1
  - spacy=2.0.16
  - sqlite=3.25.3
  - tensorboard=1.12.0
  - tensorflow=1.12.0
  - tensorflow-base=1.12.0
  - termcolor=1.1.0
  - thinc=6.12.0
  - tk=8.6.8
  - toolz=0.9.0
  - tqdm=4.28.1
  - ujson=1.35
  - urllib3=1.23
  - werkzeug=0.14.1
  - wheel=0.32.3
  - wrapt=1.10.11
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
  - pip:
    - fr-core-news-sm==2.0.0
    - msgpack==0.5.6

